import { ICrosshair } from "../types";

export const crosshairInitialSettings: ICrosshair = {
  color: "0",
  hexColorEnabled: false,
  hexColorValue: "#FFFFFF",
  outlinesEnabled: true,
  outlinesThickness: "1",
  outlinesAlpha: "0.5",
  dotEnabled: false,
  dotThickness: "2",
  dotAlpha: "1",
  innerEnabled: true,
  innerThickness: "2",
  innerLength: "6",
  innerVerticalEnabled: false,
  innerVerticalLength: "6",
  innerOffset: "3",
  innerAlpha: "0.8",
  outerEnabled: true,
  outerThickness: "2",
  outerLength: "2",
  outerVerticalEnabled: false,
  outerVerticalLength: "2",
  outerOffset: "10",
  outerAlpha: "0.35",
};
